allow forcing deployment on context status check errors
moneymeets/ghd pull request #24
Opened 2020-12-01 00:33 UTC by stohrendorf

/cc @pchorus @dniggemann

2020-12-01 07:19 UTC, mm-matthias approved these changes

2020-12-01 07:23 UTC, zyv requested changes
Ich finde die Struktur von Commits gut, war angenehmen zu reviewen. Nur ein Vorschlag Richtung Enum habe ich, da du dich mit Type-Safety beschäftigt hast.

2020-12-01 07:23 UTC, zyv commented on docker/commands/gui.py
> +                DeploymentPayload(type="initial", from_ref="", to_ref=ref),
I would have also extracted types as an Enum.

2020-12-01 07:54 UTC, marns93 requested changes
Nice! :+1: 
Just two small things:
1. Could you please link the ticket MD-4873 with d8a4f4d
2. Is it possible to get feedback after choosing force-deploy or abort? At this moment, both cases show the deployment list

2020-12-01 09:35 UTC, zyv approved these changes
Von meiner Seite sieht gut aus, Kommentar von Marcel zum Feedback finde ich allerdings auch sinnvoll.

2020-12-03 10:22 UTC, marns93 approved these changes
Habe getestet, für mich funktioniert das alles.
Auch die Status Meldung bei einem Force-Deploy erscheint, wenn das Deployment erfolgreich getriggert wurde.

2020-12-03 12:07 UTC, zyv approved these changes

2020-12-03 13:02 UTC, merged