feat: update python poetry linter
moneymeets/ghd pull request #36
Opened 2021-12-27 13:20 UTC by catcombo

1. Bump Python version to 3.10 and update dependencies
2. Replace `flake8` with `add-traling-comma`
3. Update test toolchain
4. Move project source files from docker directory to the root folder

2021-12-27 14:14 UTC, marns93 requested changes

2021-12-27 14:14 UTC, marns93 commented on pyproject.toml
> +pytest-django = "*"
I think we can use just pytest, or?

2021-12-27 16:34 UTC, catcombo commented on pyproject.toml
> +pytest-django = "*"
Sure!

2021-12-28 07:39 UTC, marns93 approved these changes

2021-12-28 07:50 UTC, merged