feat: verify GitHub check suites statuses before deployment
moneymeets/ghd pull request #37
Opened 2022-01-06 09:17 UTC by catcombo

1. Use [GitHub check suites](https://docs.github.com/en/rest/guides/getting-started-with-the-checks-api) to verify commit status before deployment. A check suite is a collection of the check runs created by a single GitHub App for a specific commit. Check suites summarize the status and conclusion of the check runs that a suite includes. Previously we used `required_context` argument when [creating a new GitHub deployment](https://docs.github.com/en/rest/reference/deployments#create-a-deployment) to force deploy or to verify all check runs that must be in success state. But it doesn't work for [moneymeets-app](https://github.com/moneymeets/moneymeets-app) because CI pipeline can have some check runs in a skipped state.
2. Replace `--require-context` flag with `--force-deploy`. Need to update https://github.com/moneymeets/moneymeets-app/blob/master/.github/workflows/ci.yml#L205

I've already done deployment tests on my private repository. But we need to test new ghd version against our real repositories and specific cases:

- [ ] Test deployment to dev
- [ ] Test deployment to dev when summary commit CI status is failed
- [ ] Test deployment to dev when summary commit CI status is success, but some of the runs are in skipped state
- [ ] Test promote from dev to test
- [ ] Test promote from test to live when deploying to test is not finished yet
- [ ] Test `--force-deploy` flag for deployment from command line

2022-01-06 10:07 UTC, pchorus requested changes
LGTM! 👍🏻 

@catcombo So from your explanation I understand that the outcome of the check suite is the conclusion of a workflow, which is "success" for the moneymeets-app dev deployment even if there are jobs that are skipped, right?

I wonder what the conclusion "neutral" means and if we need to take that into account as well.

I added some minor suggestions. Code is understandable. I haven't tested it though.

2022-01-06 10:07 UTC, pchorus commented on commands/__init__.py
> +    "--force-deploy",
Since the command is named `deploy`, I would prefer `--force` as name for the parameter over `--force-deploy` to avoid redundancy.

2022-01-06 10:07 UTC, pchorus commented on commands/__init__.py
> +    print(f"  force deploy       {bool_to_str(force_deploy)}")
See above: "force" instead of "force deploy".

2022-01-06 10:07 UTC, pchorus commented on commands/utils.py
> +                f"Deployment of {ref} to {environment} failed, because there are some check not in a success state",
```suggestion
                f"Deployment of {ref} to {environment} failed, because there are some checks not in a success state.",
```

2022-01-06 10:25 UTC, catcombo commented
> @catcombo So from your explanation I understand that the outcome of the check suite is the conclusion of a workflow, which is "success" for the moneymeets-app dev deployment even if there are jobs that are skipped, right?

Regarding the [auto dev deployment in moneymeets-app](https://github.com/moneymeets/moneymeets-app/blob/master/.github/workflows/ci.yml#L205) we anyway have to use the `--force` flag because we run deploy command inside GitHub workflow which is in `in progress` state. But for any other cases (promoting to test or manual deployment to dev) you got me right.

> I wonder what the conclusion "neutral" means and if we need to take that into account as well.

I think we can add a new status when we encounter it. But I don't know what neutral means too.

2022-01-06 17:06 UTC, mm-matthias commented
I don't have time to check this throughly, so I'll rely on you guys to get this right.

Maybe keep in mind that this repository is public, so we should probably keep reference to our internal repositories and workflows to a minimum.

2022-01-06 17:35 UTC, catcombo commented
> I don't have time to check this throughly, so I'll rely on you guys to get this right.

@pchorus and I have tested all the use cases. Later on, I can write some tests so that next time we don't have to check all commands manually.

> Maybe keep in mind that this repository is public, so we should probably keep reference to our internal repositories and workflows to a minimum.

Sorry, my fault. Should I remove all links and related information from the PR?

2022-01-06 17:44 UTC, mm-matthias commented
It's not critical to move from a security point of view. However, to keep the PR clean and so that it can serve as future reference, it would be nice to move the discussion unrelated to ghd itself to a different place. Maybe you can move those parts into the MD ticket?

@pchorus will probably be able to help you.

2022-01-06 18:55 UTC, catcombo commented
> It's not critical to move from a security point of view. However, to keep the PR clean and so that it can serve as future reference, it would be nice to move the discussion unrelated to ghd itself to a different place. Maybe you can move those parts into the MD ticket?

Done.

2022-01-07 06:20 UTC, pchorus commented
The PR looks good to me. So we can merge it for now to fix our issue in moneymeets-app.
However, I had a chat with @mm-matthias yesterday and both of us would prefer using as much GitHub functionality as possible and less manual checks. That would make it much easier to implement deployment stuff in and-action, for example.

Maybe we should think again about the possibilities to clean up the ci master pipeline in moneymeets-app so it does not contain skipped tasks. Then all checks could stay in GitHub and GHD would not need any change.

FYI @marns93

2022-01-07 06:20 UTC, pchorus approved these changes

2022-01-07 07:17 UTC, marns93 commented
> The PR looks good to me. So we can merge it for now to fix our issue in moneymeets-app. However, I had a chat with @mm-matthias yesterday and both of us would prefer using as much GitHub functionality as possible and less manual checks. That would make it much easier to implement deployment stuff in and-action, for example.
> 
> Maybe we should think again about the possibilities to clean up the ci master pipeline in moneymeets-app so it does not contain skipped tasks. Then all checks could stay in GitHub and GHD would not need any change.
> 
> FYI @marns93

@pchorus As I said, I'm not against it, but we have to think about it how to handle this to not copy and paste all the stuff. Let's find time to discuss this. :)

2022-01-07 07:19 UTC, marns93 approved these changes
LGTM! :+1: 

I didn't test it, but I think you did it. @catcombo @pchorus 

Please don't forget to update the docker version tag in `action.yml`

2022-01-07 09:00 UTC, merged

2022-02-04 09:38 UTC, zyv commented
@catcombo @pchorus @marns93 yes, tests in GHD is the pain point. Thanks god there are some tests of the GUI stuff, but the rest is completely untested :-/

On the other hand, I'm reluctant to prioritise this, because I would hope to keep the logic in GitHub and add deployment functionality to AndAction - so that we get a control plane and deployment tool in one, finally...

I guess we should revisit this next time when major changes will be needed in GHD.